[package]
name = "uplift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "=0.38.0"
winit = "0.30.3"
ash-window = "0.13.0"
bytemuck = "1.16.1"
